<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Museum">
    <xs:complexType>
      <xs:sequence>
        <xs:element name='Exhibitions'>
          <xs:complexType>
            <xs:sequence>
              <xs:element name='Exhibition' type='ExhibitionType' minOccurs='1' maxOccurs='unbounded'/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="ExhibitionType">
    <xs:sequence>
      <xs:element name='Description' type='xs:string'/>
      <xs:element name='Schedule'>
        <xs:complexType>
          <xs:sequence> 
            <xs:element name='StartDate' type='xs:date'/>
            <xs:element name='EndDate' type='xs:date'/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name='VisitorsPerDay'>
        <xs:complexType>
          <xs:sequence>
            <xs:element name='Adult' type='xs:positiveInteger' />
            <xs:element name='Under12' type='xs:positiveInteger' />
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name='Artist' type='xs:string'/>

      <xs:element name='ThemeCulture' type='xs:string'/>

      <xs:choice>
        <xs:element name='HistoricalPeriod' minOccurs='0'>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9][0-9]*(st|nd|rd|th) century (BC|AD)"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name='HistoricalDate' type='xs:date'/>
      </xs:choice>

    </xs:sequence>

    <xs:attribute name='id' type='xs:ID' use='required'/>
  </xs:complexType>

</xs:schema>