<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name='Exhibitions'>
		<xs:complexType>
			<xs:sequence>
				<xs:element name='Exhibition' type='ExhibitionType' minOccurs='1' maxOccurs='unbounded'/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ExhibitionType">
		<xs:sequence>
			<xs:element name='Theme'>
				<!--The exhibition title is nothing else but a Theme-->
				<xs:complexType>
					<xs:attribute name="ref" type='xs:IDREF' use='required'/>
				</xs:complexType>
			</xs:element>
			<xs:element name='Schedule'>
				<xs:complexType>
					<xs:sequence>
						<xs:element name='OpeningDate' type='xs:date'/>
						<xs:element name='ClosingDate' type='xs:date'/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name='HistoricalPeriod' type='PeriodRangeType'/>
			<xs:choice>
				<xs:element name="Artifacts">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Artifact" minOccurs="10" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="ref" type="xs:IDREF" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Collection" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="ref" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element name='Artists'>
				<xs:complexType>
					<xs:sequence>
						<xs:element name='Artist' type='ArtistType' minOccurs='1' maxOccurs='unbounded'/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name='VisitorCount'>
				<xs:complexType>
					<xs:sequence>
						<xs:element name='Adult' type='CountType'/>
						<xs:element name='UnderAge' type='CountType'/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name='id' type='xs:ID' use='required'/>
	</xs:complexType>
	<xs:complexType name="CountType">
		<xs:simpleContent>
			<xs:extension base="xs:positiveInteger">
				<xs:attribute name="unit" type="xs:string" use="required" fixed="Visitors/Day"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name='ArtistType'>
		<xs:simpleContent>
			<xs:extension base="FullNameType">
				<xs:attribute name="role" type="RoleType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name='FullNameType'>
		<xs:restriction base="xs:string">
			<xs:pattern value="\p{Lu}[\p{L}'\-]*( (\p{Lu}[\p{L}'\-]*|de|del|della|di|da|dos|van|von|der|den|le|la|bin|al))+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name='RoleType'>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Curator"/>
			<xs:enumeration value="Exhibition Architect"/>
			<xs:enumeration value="Scenographer"/>
			<xs:enumeration value="Sound and Light Engineer"/>
			<xs:enumeration value="Lighting Designer"/>
			<xs:enumeration value="Conservator"/>
			<xs:enumeration value="Graphic Designer"/>
			<xs:enumeration value="Audiovisual Producer"/>
			<xs:enumeration value="Education Coordinator"/>
			<xs:enumeration value="Registrar"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name='PeriodRangeType'>
		<xs:attribute name="from" type="CenturyType" use="required"/>
		<xs:attribute name="to" type="CenturyType" use="required"/>
	</xs:complexType>
	<xs:simpleType name='CenturyType'>
		<xs:restriction base="xs:string">
			<xs:pattern value="(([0-9]*[02-9])?1st|([0-9]*[02-9])?2nd|([0-9]*[02-9])?3rd|[0-9]*[04-9]th|[0-9]*1[123]th) century (BC|AD)"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
